/* eslint no-unused-vars: off */
/* eslint no-global-assign: off */
/* global systemDictionary */
'use strict';

systemDictionary = {
	'schlueter-fbh adapter settings': {
		en: 'Adapter settings for schlueter-fbh',
		de: 'Adaptereinstellungen für schlueter-fbh',
		ru: 'Настройки адаптера для schlueter-fbh',
		pt: 'Configurações do adaptador para schlueter-fbh',
		nl: 'Adapterinstellingen voor schlueter-fbh',
		fr: "Paramètres d'adaptateur pour schlueter-fbh",
		it: "Impostazioni dell'adattatore per schlueter-fbh",
		es: 'Ajustes del adaptador para schlueter-fbh',
		pl: 'Ustawienia adaptera dla schlueter-fbh',
		uk: 'Налаштування адаптера для schlueter-fbh',
		'zh-cn': 'schlueter-fbh的适配器设置',
	},
	username: {
		en: 'UserName',
		de: 'UserName',
		ru: 'вариант 1',
		pt: 'opção1',
		nl: 'optie1',
		fr: 'option1',
		it: 'opzione1',
		es: 'opción1',
		pl: 'opcja 1',
		uk: 'варіант1',
		'zh-cn': '选项1',
	},
	password: {
		en: 'Password',
		de: 'Password',
		ru: 'вариант 2',
		pt: 'opção2',
		nl: 'optie2',
		fr: 'option2',
		it: 'opzione2',
		es: 'opción2',
		pl: 'opcja 2',
		uk: 'варіант2',
		'zh-cn': '选项2',
	},
	customerid: {
		en: 'CustomerID',
		de: 'CustomerID',
		ru: 'вариант 2',
		pt: 'opção2',
		nl: 'optie2',
		fr: 'option2',
		it: 'opzione2',
		es: 'opción2',
		pl: 'opcja 2',
		uk: 'варіант2',
		'zh-cn': '选项2',
	},
	serial1: {
		en: 'Serial1',
		de: 'Serial1',
		ru: 'вариант 2',
		pt: 'opção2',
		nl: 'optie2',
		fr: 'option2',
		it: 'opzione2',
		es: 'opción2',
		pl: 'opcja 2',
		uk: 'варіант2',
		'zh-cn': '选项2',
	},
	timerGroup: {
		en: 'TimerGroup',
		de: 'TimerGroup',
		ru: 'вариант 2',
		pt: 'opção2',
		nl: 'optie2',
		fr: 'option2',
		it: 'opzione2',
		es: 'opción2',
		pl: 'opcja 2',
		uk: 'варіант2',
		'zh-cn': '选项2',
	},
	myColor: {
		en: 'myColor',
		de: 'meineColor',
		ru: 'Мой цвет',
		pt: 'minhaCor',
		nl: 'mijnKleur',
		fr: 'maCouleur',
		it: 'mioColore',
		es: 'miColor',
		pl: 'mójKolor',
		uk: 'мійКолір',
		'zh-cn': '我的颜色',
	},
	myColor_tooltip: {
		en: 'Description of\nmyColor',
		de: 'Beschreibung von\nmyColor',
		ru: 'Описание\nmyColor',
		pt: 'Descrição de\nmyColor',
		nl: 'Beschrijving van\nmyColor',
		fr: 'Description de\nmyColor',
		it: 'Descrizione di\nmyColor',
		es: 'Descripción de\nmyColor',
		pl: 'Opis\nmyColor',
		uk: 'Опис\nmyColor',
		'zh-cn': '\nmyColor的描述',
	},
	htmlText: {
		en: 'htmlText',
		de: 'htmlText',
		ru: 'htmlText',
		pt: 'htmlText',
		nl: 'htmlText',
		fr: 'htmlText',
		it: 'htmlText',
		es: 'htmlText',
		pl: 'htmlText',
		uk: 'htmlText',
		'zh-cn': 'htmlText',
	},
	group_extraMyset: {
		en: 'extraMyset',
		de: 'extraMyset',
		ru: 'extraMyset',
		pt: 'extraMyset',
		nl: 'extraMyset',
		fr: 'extraMyset',
		it: 'extraMyset',
		es: 'extraMyset',
		pl: 'extraMyset',
		uk: 'extraMyset',
		'zh-cn': 'extraMyset',
	},
	extraAttr: {
		en: 'extraAttr',
		de: 'extraAttr',
		ru: 'extraAttr',
		pt: 'extraAttr',
		nl: 'extraAttr',
		fr: 'extraAttr',
		it: 'extraAttr',
		es: 'extraAttr',
		pl: 'extraAttr',
		uk: 'extraAttr',
		'zh-cn': 'extraAttr',
	},
	Instance: {
		en: 'Instance',
		de: 'Instanz',
		ru: 'Инстанция',
		pt: 'Instância',
		nl: 'Instantie',
		fr: 'Instance',
		it: 'Esempio',
		es: 'Instancia',
		pl: 'Instancja',
		uk: 'Інстанція',
		'zh-cn': '例',
	},
};
